FROM node:14.17.0

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=http://localhost:8080/api/v1

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/

ADD src /usr/src/app/src
ADD public /usr/src/app/public

RUN npm install --legacy-peer-deps

ADD . .

RUN npm run-script build

EXPOSE 3000
CMD [ "npm", "start" ]
