version: '3.7'

services:
  sqlserver:
    container_name: relatorio-obra-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin@1234"
    ports:
      - "1433:1433"
    networks:
      - sql_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.2
    container_name: elasticsearch
    environment:
      node.name: "es01"
      cluster.name: "es-docker-cluster"
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "elastic"
      xpack.security.enabled: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    networks:
      - elastic-network

networks:
  sql_network:
    driver: bridge
  elastic-network:
    driver: bridge

volumes:
  elasticsearch-data-volume:
