FROM openjdk:8-jdk-alpine as build

WORKDIR /app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src
RUN dos2unix mvnw
RUN ./mvnw clean install package -DskipTests
RUN mkdir -p target/dependency
RUN cd target/dependency; jar -xf ../*.jar

FROM openjdk:8-jre-alpine

RUN apk add --no-cache tzdata

ENV TZ=America/Recife
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG DEPENDENCY=/app/target/dependency

COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

ENTRYPOINT ["java", "-cp","app:app/lib/*", "-Dspring.profiles.active=dev", "br.gov.ac.tce.licon.Application"]
