CREATE TABLE DBO.RELAT0RIO_OBRA (
    ID_RELATORIO_OBRA BIGINT IDENTITY(1,1) NOT NULL,
    DATA_ANALISE DATETIME2,
    OBSERVACAO VARCHAR(4000),
    TITULO VARCHAR(300),
    IMPORTADO BIT DEFAULT 0,
    CONSTRAINT PK_RELATORIO_AUDITORIA_OBRA PRIMARY KEY (ID_RELATORIO_OBRA)
);

CREATE TABLE DBO.ARQUIVO_RELATORIO_OBRA (
    ID_ARQUIVO_RELATORIO_OBRA BIGINT IDENTITY(1,1) NOT NULL,
    DATA_ENVIO DATETIME2,
    DESCRICAO VARCHAR(255),
    DIRETORIO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TIPO_ARQUIVO VARCHAR(255) NOT NULL,
    ID_RELATORIO_OBRA BIGINT NOT NULL,
    TIPO_ARQUIVO_RELATORIO_OBRA VARCHAR(255) NOT NULL,
    CONSTRAINT PK_ARQUIVO_RELATORIO_OBRA PRIMARY KEY (ID_ARQUIVO_RELATORIO_OBRA),
    CONSTRAINT FK_RELATORIO_OBRA FOREIGN KEY (ID_RELATORIO_OBRA) REFERENCES DBO.RELAT0RIO_OBRA(ID_RELATORIO_OBRA)
);

CREATE TABLE DBO.ITEM_OBRA (
   ID_ITEM_OBRA BIGINT IDENTITY(1,1) NOT NULL,
   CODIGO VARCHAR(200),
   FONTE VARCHAR(200),
   QUANTIDADE INT,
   PRECO_UNITARIO numeric(19,2) NOT NULL,
   MES_COLETA VARCHAR(6) NOT NULL,
   DESONERADO BIT DEFAULT 0,
   IMPORTADO BIT DEFAULT 0,
   SCORE numeric(19,2),
   ID_RELATORIO_OBRA BIGINT NOT NULL,
   CONSTRAINT PK_ITEM_OBRA PRIMARY KEY (ID_ITEM_OBRA),
   CONSTRAINT FK_RELAT0RIO_OBRA FOREIGN KEY (ID_RELATORIO_OBRA) REFERENCES DBO.RELAT0RIO_OBRA(ID_RELATORIO_OBRA)
);