CREATE TABLE SICRO_FILE_LOG (
    ID INT PRIMARY KEY IDENTITY(1,1),
    FILE_NAME NVARCHAR(255),
    MONTH_DONWLOAD NVARCHAR(20),
    YEAR_DOWNLOAD INT,
    DATE_DONWLOAD DATETIME DEFAULT GETDATE()
);

CREATE TABLE SINAPI_FILE_LOG (
    ID INT PRIMARY KEY IDENTITY(1,1),
    FILE_NAME NVARCHAR(255),
    MONTH_DONWLOAD NVARCHAR(20),
    YEAR_DOWNLOAD INT,
    DATE_DONWLOAD DATETIME DEFAULT GETDATE()
);