app: # App
  name: LICON-HOMOLOG
  pagination:
    limit:
      default: ${PAGINATION_LIMIT_DEFAULT:20}
      max: ${PAGINATION_LIMIT_MAX:100}
  files:
    repository-full-path:
    temp-folder-path: arquivos_uploads_temp
    definitive-folder-path: arquivos_uploads
    licitacoes-folder-path: licitacoes
    caronas-folder-path: caronas
    contrato-folder-path: contrato
    aditivo-contrato-folder-path: aditivo_contrato
    dispensas-folder-path: dispensas
    inexigibilidades-folder-path: inexigibilidades
    comissoes-folder-path: comissoes
    termo-referencia-folder-path: termo_referencia
    tda-licitacao-folder-path: tda_licitacao
    tda-carona-folder-path: tda_carona
    tda-dispensa-folder-path: tda_dispensa
    tda-inexigibilidade-folder-path: tda_inexigibilidade
    alerta-analise-folder-path: alerta_analise
    alerta-mensagem-folder-path: alerta_mensagem
    editais-folder-path: editais
    obra-medicao-folder-path: obra-medicao
    empenho-contrato-folder-path: empenho-contrato
  group:
    admin:
      label: "ADMINISTRADOR"
  permissao:
    admin:
      label: "ADMIN"
server:
  port: 8080
  servlet:
    context-path: /licon-api
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /licon-api/v3/api-docs.yaml
spring:
  servlet:
    multipart:
      max-request-size: 210MB
      max-file-size: 100MB
      enabled: true
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=LICON_DEV
    username: sa
    password: Oil2005iGIS
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
  rabbitmq:
    password: "123456"
    port: "5672"
    host: localhost
    username: admin
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 3
          multiplier: 2
    queue:
      name: mq.email.homolog
    exchange:
      name: mq.exchange.homolog.email
    routeKey: mq.route.homolog.email
  elasticsearch:
    host:
    user:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      org:
        hibernate:
          envers:
            default_schema: AUDITORIA
            revision_field_name: ID_AUDT
      hibernate:
        dialect: org.hibernate.spatial.dialect.sqlserver.SqlServer2008SpatialDialect
        format_sql: false
        show_sql: false
        use_sql_comments: false
        default_schema: dbo
        listeners:
          envers:
            autoRegister: true
